# Default values for the jupyter-server-operator chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Indicate the scope which this operator watches for
# JupyterServer resources.
scope:
  clusterWide: false
  # Namespaces are ignored if clusterWide is set to true.
  namespaces:
    - default

deployCrd: true  # whether to deploy the jupyterserver CRD

rescheduleOnNodeFailure: false

# Configure the kopf operator settings by providing
# a yaml object as multiline string. See
# https://kopf.readthedocs.io/en/stable/configuration/
# for configuraiton options.
kopfOperatorSettings: |
  watching:
    # This can fix a problem of a watch stream suddenly falling
    # silent, see https://github.com/nolar/kopf/issues/762#issuecomment-838423267
    client_timeout: 600

image:
  repository: ableuler/jupyter-server-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
sessionIngress:
  # Use the following annotations in the ingress object of every session
  annotations: |
    {
      cert-manager.io/cluster-issuer: letsencrypt-production,
      kubernetes.io/ingress.class: nginx,
      kubernetes.io/tls-acme: "true",
      nginx.ingress.kubernetes.io/proxy-body-size: "0",
      nginx.ingress.kubernetes.io/proxy-buffer-size: 8k,
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off",
    }
  # If set to a value, the same certificate and secret will be used for every session
  # If not set then a new certificte will be created for every session
  tlsSecretName: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
