apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sessions.renku.io
spec:
  scope: Namespaced
  group: renku.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                notebookImage:
                  type: string
                  default: jupyter/minimal-notebook:latest

                notebookDefaultPath:
                  type: string
                  default: /lab

                # TODO: Automatically fetch and inline schema
                # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
                resources:
                  description: "Regular resource requests, will be set on the main notebook container."
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

                host:
                  type: string
                path:
                  type: string
                  default: "/"

                auth:
                  type: object
                  properties:
                    # Accepted values are token and OIDC
                    kind:
                      type: string
                      default: token
                    token:
                      type: string
                      default: ""
                    oidc:
                      type: object
                      properties:
                        issuerUrl:
                          type: string
                        clientId:
                          type: string
                        clientSecret:
                          type: string
                        userId:
                          type: string
                        cookieSecret:
                          type: string

                # TODO: Automatically fetch and inline schemas for the below sections.

                # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
                extraInitContainers:
                  description: "Extra init container specs, will be added to statefulset pod template."
                  type: array
                  default: []
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true

                # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
                extraContainers:
                  description: "Extra container specs, will be added to statefulset pod template."
                  type: array
                  default: []
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true

                # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
                extraVolumes:
                  description: "Extra volume specs, will be added to the statefulset pod template."
                  type: array
                  default: []
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true

                # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
                extraImagePullSecrets:
                  description: "Extra image pull sedret specs, will be added to the notebook container template."
                  type: array
                  default: []
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true

                # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
                extraVolumeMounts:
                  description: "Extra volume mount specs, will be added to the notebook container template."
                  type: array
                  default: []
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true

                # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
                extraEnv:
                  description: "Extra env variables, will be added to the notebook container template."
                  type: array
                  default: []
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true

                # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
                extraPVCs:
                  description: "Extra PVC specs, will be part of the custom resource object."
                  type: array
                  default: []
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true

  names:
    kind: Session
    plural: sessions
    singular: session
