{{- if .Values.serviceAccount.create -}}
apiVersion: v1
# TODO: Add options for a cluster- or namespaced scoped operator here.
kind: ServiceAccount
metadata:
  name: {{ include "jupyter-server-operator.serviceAccountName" . }}
  labels:
    {{- include "jupyter-server-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{ if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jupyter-server-operator.fullname" . }}
  labels:
    {{- include "jupyter-server-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jupyter-server-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "jupyter-server-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
---
{{ if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jupyter-server-operator.fullname" . }}
  labels:
    {{- include "jupyter-server-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
    resources:
      - statefulsets
      - ingresses
      - services
      - secrets
      - configmaps
      - persistentvolumeclaims
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups:
      - "renku.io"
    resources:
      - sessions
    verbs:
      - get
      - list
      - watch
      - patch
{{- end }}


